### ISSUE TITLE
ffmpeg on heroku fails

### ISSUE THREAD

**Issue by droopified** [RafaelSolVargas/Vulkan#24]
i dont know whats to do here. 

2022-07-31T21:35:23.471246+00:00 app[worker.1]: Starting Vulkan...
2022-07-31T21:35:23.471642+00:00 app[worker.1]: Vulkan is now operating.
2022-07-31T21:35:31.581494+00:00 app[worker.1]: Starting Process =test=
2022-07-31T21:35:32.721234+00:00 app[worker.1]: [ERROR IN PLAY SONG] -> ffmpeg was not found., <class 'discord.errors.ClientException'>
2022-07-31T21:35:32.727022+00:00 app[worker.1]: Exception ignored in: <function AudioSource.__del__ at 0x7fec77d57910>
2022-07-31T21:35:32.727036+00:00 app[worker.1]: Traceback (most recent call last):
2022-07-31T21:35:32.727051+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.10/site-packages/discord/player.py", line 127, in __del__
2022-07-31T21:35:32.727137+00:00 app[worker.1]: Process =test= sended command VCommandsType.SLEEPING
2022-07-31T21:35:32.727281+00:00 app[worker.1]: self.cleanup()
2022-07-31T21:35:32.727294+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.10/site-packages/discord/player.py", line 247, in cleanup
2022-07-31T21:35:32.727431+00:00 app[worker.1]: self._kill_process()
2022-07-31T21:35:32.727443+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.10/site-packages/discord/player.py", line 198, in _kill_process
2022-07-31T21:35:32.727561+00:00 app[worker.1]: proc = self._process
2022-07-31T21:35:32.727604+00:00 app[worker.1]: AttributeError: 'FFmpegPCMAudio' object has no attribute '_process'

C:\Users\test\Desktop\Vulkan-1.4>heroku buildpacks:add --index 1 https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git
 »   Error: The buildpack https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git is already set on your app.

C:\Users\test\Desktop\Vulkan-1.4>heroku buildpacks:add --index 1 https://github.com/xrisk/heroku-opus.git
 »   Error: The buildpack https://github.com/xrisk/heroku-opus.git is already set on your app.

C:\Users\test\Desktop\Vulkan-1.4>heroku buildpacks
=== droopiediscordbot Buildpack URLs
1. heroku/python
2. https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git
3. https://github.com/xrisk/heroku-opus.git

C:\Users\test\Desktop\Vulkan-1.4>

**Comment by RafaelSolVargas** [comment]
Verify if the order of your buildpacks in Heroku are the same as follows:

![image](https://user-images.githubusercontent.com/86136313/182047645-2fcc68f4-42ce-45b1-9cd2-cf2f832a9af1.png)
