### ISSUE TITLE
no audio

### ISSUE THREAD

**Issue by droopified** [RafaelSolVargas/Vulkan#25]
i hit that !play link in chat and all the messages get posted with buttons and all but no audio when the bot joins the channel. ran the log and i only see this 

2022-07-31T21:57:10.518563+00:00 heroku[worker.1]: Restarting
2022-07-31T21:57:10.532088+00:00 heroku[worker.1]: State changed from up to starting
2022-07-31T21:57:11.162954+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2022-07-31T21:57:11.534332+00:00 heroku[worker.1]: Process exited with status 0
2022-07-31T21:57:14.580870+00:00 heroku[worker.1]: Starting process with command `python main.py`
2022-07-31T21:57:15.000000+00:00 app[api]: Build succeeded
2022-07-31T21:57:15.188259+00:00 heroku[worker.1]: State changed from starting to up
2022-07-31T21:57:18.145757+00:00 app[worker.1]: Starting Vulkan...
2022-07-31T21:57:18.146145+00:00 app[worker.1]: Vulkan is now operating.
2022-07-31T21:57:27.037497+00:00 app[worker.1]: Starting Process =TeaBaggers United=
2022-07-31T21:57:28.420013+00:00 app[worker.1]: Process =TeaBaggers United= sended command VCommandsType.NOW_PLAYING
2022-07-31T21:57:28.421411+00:00 app[worker.1]: Process =TeaBaggers United= sended command VCommandsType.SLEEPING
2022-07-31T21:58:52.702273+00:00 app[worker.1]: Ignoring exception in view <PlayerView timeout=6000 children=9> for item <PlayButton style=<ButtonStyle.secondary: 2> url=None disabled=False label='Play' emoji=<PartialEmoji animated=False name='▶️' id=None> row=None>:
2022-07-31T21:58:52.702766+00:00 app[worker.1]: Traceback (most recent call last):
2022-07-31T21:58:52.702790+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.10/site-packages/discord/ui/view.py", line 375, in _scheduled_task
2022-07-31T21:58:52.702791+00:00 app[worker.1]: await item.callback(interaction)
2022-07-31T21:58:52.702798+00:00 app[worker.1]: File "/app/UI/Buttons/PlayButton.py", line 17, in callback
2022-07-31T21:58:52.702799+00:00 app[worker.1]: response = await handler.run()
2022-07-31T21:58:52.702806+00:00 app[worker.1]: File "/app/Handlers/ResumeHandler.py", line 21, in run
2022-07-31T21:58:52.702807+00:00 app[worker.1]: queue.put(command)
2022-07-31T21:58:52.702814+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.10/multiprocessing/queues.py", line 88, in put
2022-07-31T21:58:52.702815+00:00 app[worker.1]: raise ValueError(f"Queue {self!r} is closed")
2022-07-31T21:58:52.702828+00:00 app[worker.1]: ValueError: Queue <multiprocessing.queues.Queue object at 0x7f1b10df2080> is closed

**Comment by RafaelSolVargas** [comment]
Can you show me which link exactly you used?

**Comment by RafaelSolVargas** [comment]
In this issue: https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest/issues/60 someone are reporting that after the stack `heroku-22` this module of heroku buildpack doesn't work anymore. 
I checked the stack that i'm using Heroku and it's `heroku-20`.
Please, verify what stack you are using and let me know!

The stack is an attribute of your heroku application, you can find it in the page `Settings`

**Comment by droopified** [comment]
yup changing it to heroku 20 worked! thank you for all the work on this! everyone LOVES the buttons!!!

**Comment by RafaelSolVargas** [comment]
Thanks for the feedback! If possibly, leave a star in this project, it motivates me to keep going :D
