### ISSUE TITLE
ValueError: mutable default <class 'discord.utils._MissingSentinel'> for field name is not allowed: use default_factory

### ISSUE THREAD

**Issue by atikiN589** [RafaelSolVargas/Vulkan#40]
When trying to run Vulkan, following error message appears: ValueError: mutable default <class 'discord.utils._MissingSentinel'> for field name is not allowed: use default_factory.

Full log:
```
Traceback (most recent call last):
  File "/home/nikitaka/Documents/Vulkan-master/Vulkan-master/main.py", line 1, in <module>
    from Music.VulkanInitializer import VulkanInitializer
  File "/home/nikitaka/Documents/Vulkan-master/Vulkan-master/Music/VulkanInitializer.py", line 5, in <module>
    from Music.VulkanBot import VulkanBot
  File "/home/nikitaka/Documents/Vulkan-master/Vulkan-master/Music/VulkanBot.py", line 3, in <module>
    from discord.ext.commands.errors import CommandNotFound, MissingRequiredArgument
  File "/home/nikitaka/.local/lib/python3.11/site-packages/discord/ext/commands/__init__.py", line 18, in <module>
    from .flags import *
  File "/home/nikitaka/.local/lib/python3.11/site-packages/discord/ext/commands/flags.py", line 57, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/lib64/python3.11/dataclasses.py", line 1220, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/lib64/python3.11/dataclasses.py", line 1210, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'discord.utils._MissingSentinel'> for field name is not allowed: use default_factory
```
I think it's not a problem with the bot itself, but with the discord.py package
P.S. I did pip install -r requirements.txt

**Comment by RafaelSolVargas** [comment]
Hello!
Like you said, the problem occurs in the discord.py library, i can't help with that. You can go to their github and report this issue.
Issue of pycord: https://github.com/Pycord-Development/pycord/issues
