### ISSUE TITLE
Bot does not like mobile Youtube links (m.youtube.com)

### ISSUE THREAD

**Issue by Darthwayne** [RafaelSolVargas/Vulkan#48]
**Describe your context**:
Bot fails to play music when there is an 'm.' before the link, for example: /play https://m.youtube.com/watch?v=bIgVecA77Qo will cause the bot to fail. But if you remove the 'm.' (https://youtube.com/watch?v=bIgVecA77Qo) the bot will play the Youtube link just fine. I believe this is just a quality of life request, if a user inputs a m.youtube link, have the bot remove the 'm.' part?

**The path to the bug**:
After performing /play https://m.youtube.com/watch?v=bIgVecA77Qo, the console outputs error:
```
[ERROR IN PLAYHANDLER] -> Traceback (most recent call last):
  File "/home/container/Handlers/PlayHandler.py", line 33, in run
    musicsInfo = await self.__searcher.search(track)
  File "/home/container/Music/Searcher.py", line 21, in search
    raise InvalidInput(self.__messages.UNKNOWN_INPUT, self.__messages.UNKNOWN_INPUT_TITLE)
Config.Exceptions.InvalidInput
 {<class 'Config.Exceptions.InvalidInput'>}
```
**Screenshots**:
![image](https://github.com/RafaelSolVargas/Vulkan/assets/115687000/83421e7e-2137-490d-b9b8-9f08741499c7)
![image](https://github.com/RafaelSolVargas/Vulkan/assets/115687000/52ccabc2-c2f9-4fed-a386-f2ba8cd88f08)
![image](https://github.com/RafaelSolVargas/Vulkan/assets/115687000/09185d9c-d7b8-4146-9b1c-88e99016a784)

**Comment by RafaelSolVargas** [comment]
Fixed

**Comment by UVRadiation** [comment]
Same thing with videos with limited access (by link)

**Comment by RafaelSolVargas** [comment]
Can you give an example?

**Comment by UVRadiation** [comment]
Thanks for the quick reply! Didn't describe the problem very correctly. Not a song, but a playlist. [ Link to playlist](https://youtube.com/playlist?list=PLmEUdHd9IrmOEpC4vcRjj0IqFyssCHIfp&si=B1MTessdux4ZW5Cj) 
![Screenshot 2024-10-28 at 03-51-09 image](https://github.com/user-attachments/assets/fe0714e0-3e09-4362-9bcf-ba93624da59a)

`[ERROR IN PLAYHANDLER] -> Traceback (most recent call last):
  File "/home/grisha/MusicBot/Handlers/PlayHandler.py", line 33, in run
    musicsInfo = await self.__searcher.search(track)
  File "/home/grisha/MusicBot/Music/Searcher.py", line 21, in search
    raise InvalidInput(self.__messages.UNKNOWN_INPUT, self.__messages.UNKNOWN_INPUT_TITLE)
Config.Exceptions.InvalidInput
 {<class 'Config.Exceptions.InvalidInput'>}`
