### ISSUE TITLE
Bug ImportError: cannot import name 'SlashCommandOptionType' from 'discord.enums' 

### ISSUE THREAD

**Issue by subhampro** [RafaelSolVargas/Vulkan#59]
![image](https://github.com/RafaelSolVargas/Vulkan/assets/33375250/074604ba-f8db-4af2-989b-e9bee026bf82)

```
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Vulkan-master\main.py", line 1, in <module>
    from Music.VulkanInitializer import VulkanInitializer
  File "C:\Users\Administrator\Desktop\Vulkan-master\Music\VulkanInitializer.py", line 3, in <module>
    from discord.bot import Bot
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\bot.py", line 40, in <module>
    from .cog import CogMixin
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\cog.py", line 38, in <module>
    from .commands import (
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\commands\__init__.py", line 27, in <module>
    from .core import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\commands\core.py", line 49, in <module>
    from ..enums import MessageType, SlashCommandOptionType, try_enum
ImportError: cannot import name 'SlashCommandOptionType' from 'discord.enums' (C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\enums.py)
```

**Comment by RafaelSolVargas** [comment]
Are you sure that the "discord" library installed on your computer is the required to execute the Vulkan project?
Here we use py-cord

**Comment by subhampro** [comment]
![image](https://github.com/RafaelSolVargas/Vulkan/assets/33375250/29b41008-2abb-420a-a937-f9b932c85f7c)

Yes brother !! Check this out :)

**Comment by subhampro** [comment]
![image](https://github.com/RafaelSolVargas/Vulkan/assets/33375250/d708971f-582c-445c-85bb-993fb017a542)
here is test result !

**Comment by RafaelSolVargas** [comment]
> Yes brother !! Check this out :)

You have three Python Discord libraries that conflict with each other due to sharing the same import name. To address this issue, you can either delete all existing Python libraries and then install only the ones required for this project using the following command

```pip install -r requirements.txt``` where requirements.txt is a file in the project root

Alternatively, you can create a Python environment, which functions as a dedicated Python instance confined to a specific folder on your Windows system. This environment will only contain the required libraries for the project."

https://docs.python.org/3/library/venv.html
