### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MaximalGaming** [RafaelSolVargas/Vulkan#75]
discord.py is already installed but not getting pulled by the code

**C:\Users\harsh\Downloads\Vulkan-15.3\Vulkan-15.3>python main.py
Traceback (most recent call last):
  File "C:\Users\harsh\Downloads\Vulkan-15.3\Vulkan-15.3\main.py", line 1, in <module>
    from Music.VulkanInitializer import VulkanInitializer
  File "C:\Users\harsh\Downloads\Vulkan-15.3\Vulkan-15.3\Music\VulkanInitializer.py", line 3, in <module>
    from discord.bot import Bot
ModuleNotFoundError: No module named 'discord.bot'**

**Comment by MaximalGaming** [comment]
Now i solved that but this is the new error

![image](https://github.com/user-attachments/assets/4195ea21-f837-4ff1-8cf1-951b87fd503a)

![image](https://github.com/user-attachments/assets/c927e1b2-a644-478a-9793-f89c150b1d58)
